name: Deploy FibonacciK8s
on:
  push:
    branches:
      - main
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    permissions:
      contents: 'read'
      id-token: 'write'
 
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t dennishenderson/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true dennishenderson/react-test npm test
 
      - name: Set Identity Provider
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/647716002258/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'github-deployer@fibonacci-k8s-370014.iam.gserviceaccount.com'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: fibonacci-k8s-370014
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-east5-c
 
      - name: Build
        run: |-
          docker build -t dennishenderson/multi-client-k8s-gh:latest -t dennishenderson/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t dennishenderson/multi-server-k8s-pgfix-gh:latest -t dennishenderson/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t dennishenderson/multi-worker-k8s-gh:latest -t dennishenderson/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker
 
      - name: Push
        run: |-
          docker push dennishenderson/multi-client-k8s-gh:latest
          docker push dennishenderson/multi-server-k8s-pgfix-gh:latest
          docker push dennishenderson/multi-worker-k8s-gh:latest
 
          docker push dennishenderson/multi-client-k8s-gh:${{ env.SHA }}
          docker push dennishenderson/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          docker push dennishenderson/multi-worker-k8s-gh:${{ env.SHA }}
 
      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=dennishenderson/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=dennishenderson/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=dennishenderson/multi-worker-k8s-gh:${{ env.SHA }}